name: build

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
      - 'trunk'
    tags-ignore:
      - '**'

env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
        with:
          lfs: true
      - uses: actions/setup-java@v3.13.0
        with:
          distribution: 'zulu'
          java-version: 19
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true

      - run: ./gradlew build verifyPaparazziDebug
        env:
          ORG_GRADLE_PROJECT_SA4P_POCKET_CONSUMER_KEY: ${{ secrets.SA4P_POCKET_CONSUMER_KEY }}

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: reports
          path: app/build/reports
          if-no-files-found: error

      - uses: actions/upload-artifact@v3
        with:
          name: sa4p-debug.apk
          path: app/build/outputs/apk/debug/sa4p-debug.apk
          if-no-files-found: error

      - uses: actions/upload-artifact@v3
        with:
          name: sa4p-release-upload-signed.apk
          path: app/build/outputs/apk/release/sa4p-release.apk
          if-no-files-found: error

      - uses: actions/upload-artifact@v3
        with:
          name: mappings
          path: app/build/outputs/mapping/release
          if-no-files-found: error
